from .comparative_genomics import ComparativeGenomicsMixin as ComparativeGenomics
from .cross_references import CrossReferencesMixin as CrossReferences
from .information import InformationMixin as Information